locale: "en"
title: marshall houston
description: >-
  thoughts on engineering leadership, ai-augmented software engineering, and building teams.
github_username: marshallhouston
minimal_mistakes_skin: dark
search: true

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDORtVxhw"
    category_name: "Announcements"
    category_id: "DIC_kwDORtVxh84C5wnf"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "dark"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
repository: marshallhouston/marshallhouston.github.io
permalink: /:categories/:title/
future: true
paginate: 5
paginate_path: /page:num/

collections:
  kernels:
    output: false

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "marshall houston"
  avatar : "/assets/images/marshall.png"
  bio    : "writing about the cosmic farmland"
  links:
    - label: "website"
      icon: "fas fa-fw fa-link"
      url: "https://marshallhouston.github.io"
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marshallhouston"
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/marshallhouston"
    - label: "rss feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

footer:
  links:
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marshallhouston"
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/marshallhouston"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
