title: Marshall Houston
description: >-
  thoughts on engineering leadership, AI-augmented software engineering, and building teams.
github_username: marshallhouston
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "Marshall Houston"
  avatar : "/assets/images/marshall.png"
  bio    : "writing about the cosmic farmland"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://marshallhouston.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marshallhouston"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/marshallhouston"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
